kind: pipeline
name: Pipeline

steps:
- name: build
  image: maven:3-alpine
  commands:
  - mvn package
  volumes:
  - name: cache
    path: /root/.m2

- name: deploy
  image: maven:3-alpine
  commands:
  - cd target
  - ls  
      
services:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: twogghub/java-elk
    tags:
      - 1.0.2
      - latest
  when:
    branch:
    - master

volumes:
- name: cache
  host:
    path: /home/cache/.m2      