kind: pipeline
name: Pipeline

steps:
- name: build
  image: maven:3-alpine
  commands:
  - mvn package

- name: deploy
  image: maven:3-alpine
  commands:
  - cd target
  - ls  
      
services:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: twogghub/java-elk
    tags:
      - 1.0.1
  when:
    branch:
    - master
   