kind: pipeline
name: Pipeline

steps:
  - name: dependencies
    image: maven:alpine
    commands:
      - mvn --quiet --batch-mode dependency:tree

  - name: test
    image: maven:alpine
    commands:
      - mvn --quiet --batch-mode test

  - name: build_jar
    image: maven:alpine
    commands:
    - mvn --batch-mode clean package

  - name: deploy
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: twogghub/java-elk
      file: Dockerfile
      tags:
        - 1.0.1
    when:
      branch:
      - master
   