kind: pipeline
name: Pipeline

steps:
  - name: dependencies
    image: maven:alpine
    commands:
      - mvn dependency:tree

  - name: test
    image: maven:alpine
    commands:
      - mvn test

  - name: build
    image: maven:alpine
    commands:
    - mvn clean package

  - name: deploy
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: twogghub/java-elk
      file: Dockerfile
      tags:
        - latest
    when:
      branch:
      - master
   