kind: pipeline
name: Pipeline

steps:

  - name: test
    image: maven:alpine
    commands:
      - mvn -Dtest=SpringBootRestTestClient test

  - name: build
    image: maven:alpine
    commands:
    - mvn clean package