kind: pipeline
name: Pipeline

steps:

  - name: test
    image: maven:alpine
    commands:
      - mvn test

  - name: build
    image: maven:alpine
    commands:
    - mvn clean install

  - name: deploy
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: twogghub/java-elk
      tags:
        - latest
    when:
      branch:
      - master