kind: pipeline
name: Pipeline

steps:

  - name: test
    image: maven:alpine
    commands:
      - mvn -Dtest=SpringBootRestTestClient test

  - name: build
    image: maven:alpine
    commands:
    - mvn clean package

  - name: deploy
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: twogghub/java-elk
      context: java-sbrest/
      tags:
        - 0.1
    when:
      branch:
      - master